### ISSUE TITLE
identify talents

### ISSUE THREAD

**Issue by mastercyb** [cyber-valley/rockets#30]
## tasks
- create questionary 
- self-completion by managers
- check, interview and correction of questionary
- self-completion by workers
- check, interview by managers

 ## questionary

- introduction
	- briefly explain the purpose of the interview
	- reassure confidentiality and encourage honesty
	- explain that open conversation will give them more opportunities
	- explain that on word or even one sentence answers is not the best way to answer
	- engage in deeper conversation on every question
- your personal strengths
	- what do you love doing that you're really good at?
		- daily tasks
		- hobbies
		- or anything
	- what do your friends or family say you're really good at?
- learning from life
	- what kind of work do you enjoy doing the most?
	- have you learned any new skills lately, except learning english? how did you learn them?
	- have you learned to do something difficult? how did you learn it?
	- tell me about a big change you've adapted to. how did you manage it?
- problem-solving
	- when you have a big job to do, how do you plan to get it done?
	- can you share a story where you had to fix or solve a difficult problem?
	- when something unexpected happens, how do you figure out what to do?
- teamwork
	- describe you comfortable role in the team
		- leader
			- guides the team's direction and strategy
			- makes final decisions
			- motivates and supports team members
		- doer
			- executes tasks and projects
			- focuses on getting things done
			- often possesses specialized skills relevant to the tasks at hand
		- thinker
			- generates ideas and creative solutions
			- focuses on innovation and problem-solving
			- provides insights and perspectives that guide the team's approach
		- supporter
			- ensures team harmony and communication
			- assists with logistics and administrative needs
			- provides support to other team members as needed
	- how do you help your family or friends with their tasks?
- creativity
	- do you think you are creative person?
	- what do you love to create?
- dreams for the future
	- what makes you happy to work hard?
	- what’s something big you dream of doing in the future?
	- how can you use your talents to achieve this dream?
- closing
	- is there anything you are proud of that you want to share?
	- do you have any questions or anything you want to add?

**Comment by mastercyb** [comment]
https://github.com/cyber-valley/rockets/issues/44

**Comment by merkliubovv** [comment]
Add bio questions:

- your name? age?
- where were you born and raised?
- what do your parents do?
- do you have any siblings?
- which school did you attend? how many grades did you complete?
- which subjects did you study and enjoy studying the most?
- what did you love to do the most in your childhood and could do for hours?
- when you were little, what did you want to be when you grow up?
- have you traveled to other parts of Indonesia? where?
- do you use computer? for what tasks?
- do you read books? what is your favorite book? do you watch movies?
- what is your job experience? when did you start work and what did you do?

- do you like to plan your day, make schedules, and follow them? example, what time you wake up, what time you have food, what time you do something?
- do you like sport? what kind of sport?
- do play any musician instruments?
- do you have hobby (dancing, painting, playing or something else?) in present or in the past?
