### ISSUE TITLE
trim sheep hoofs

### ISSUE THREAD

**Issue by saint-Joy** [cyber-valley/rockets#369]
trim hoofs till 02.06.2024

**Comment by kesapayu** [comment]
- [ ] The sheep's hoof cutting is complete![IMG_20240529_161303.jpg](https://github.com/cyber-valley/rockets/assets/157117104/de5ac8e9-610f-472b-88b7-e46b193c7cde)

![Screenshot_2024-05-29-16-42-53-141_com.miui.gallery.jpg](https://github.com/cyber-valley/rockets/assets/157117104/fa4160da-9f6f-4cad-a5a0-ba794dec4cdc)
