### ISSUE TITLE
Покупки (на выезде)

### ISSUE THREAD

**Issue by DiotimaEva** [cyber-valley/rockets#382]
1 Монитор 50 дюймов, 1920на1080 
2 Маленький провод hdmi 
3 Инструменты для сада: ведра, веревки для бамбука, хорошие лопаты, секаторы, перчатки 
4 Детская деревянная площадка возле овец 
5 Инструменты по типу отверток 
6 Большие удлинитель 
7 Икеевский стол 

Тулинг:
2 лопаты штыковая 
Секатор 
Серп 
Пила побольше 
Лопатка 
Ведро 
Спрейер для ним масла 
Тележка (4-5)

**Comment by DiotimaEva** [comment]
3 больших бака переработки 
15 маленьких баков

**Comment by merkliubovv** [comment]
не купили:
ведра, секаторы, серпы, детскую деревянную площадку, стол (икеа), тележки (взяли только 2), баки для переработки, грабли как у Путу,
